version: "3"
services:
  db-master:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "qwer1595@!"
      MYSQL_ROOT_PASSWORD: "qwer1595@!"
    ports:
      - "3307:3306"
    volumes:
      - my-db-master:/var/lib/mysql
      - my-db-master:/var/lib/mysql-files
      - ./master/my.cnf:/etc/mysql/my.cnf
    networks:
      - net-mysql

  db-slave:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "qwer1595@!"
      MYSQL_ROOT_PASSWORD: "qwer1595@!"
    ports:
      - "3308:3306"
    volumes:
      - my-db-slave:/var/lib/mysql
      - my-db-slave:/var/lib/mysql-files
      - ./master/my.cnf:/etc/mysql/my.cnf
    networks:
      - net-mysql

volumes:
  my-db-master:
  my-db-slave:

networks:
  net-mysql:
    driver: bridge
